version: '3.8'

services:
  app:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=database_dev
      - DB_NAME_TEST=database_test
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database_dev
      MYSQL_DATABASE_TEST: database_test
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:

